"""add sponsor profile and certificate snapshot fields

Revision ID: 051cc63bc6c9
Revises: f86fae9d0a77
Create Date: 2026-08-23 19:01:23.828742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051cc63bc6c9'
down_revision: Union[str, None] = 'f86fae9d0a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('national_registry_id', sa.String(), server_default='', nullable=False),
    sa.Column('state_registry_ids', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), server_default='', nullable=False),
    sa.Column('contact_email', sa.String(), server_default='', nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_sponsor_profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attempts', sa.Column('cert_course_title', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('cert_field_of_study', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('cert_delivery_method', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('cert_credit_award', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('attempts', sa.Column('cert_question_count', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('cert_sponsor_name', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('cert_sponsor_registry_id', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('cert_sponsor_state_registry_ids', sa.Text(), nullable=True))
    op.add_column('attempts', sa.Column('cert_issued_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Singleton row, id 1, empty strings - see app/models/sponsor_profile.py.
    # Inserted here rather than left to be created on first admin edit, so
    # the admin page always has a record to load and PATCH against.
    op.execute(
        "INSERT INTO sponsor_profile (id, name, national_registry_id, website, contact_email, address) "
        "VALUES (1, '', '', '', '', '')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'cert_issued_at')
    op.drop_column('attempts', 'cert_sponsor_state_registry_ids')
    op.drop_column('attempts', 'cert_sponsor_registry_id')
    op.drop_column('attempts', 'cert_sponsor_name')
    op.drop_column('attempts', 'cert_question_count')
    op.drop_column('attempts', 'cert_credit_award')
    op.drop_column('attempts', 'cert_delivery_method')
    op.drop_column('attempts', 'cert_field_of_study')
    op.drop_column('attempts', 'cert_course_title')
    op.drop_table('sponsor_profile')
    # ### end Alembic commands ###
