"""add question kind and feedback, course pass ratio, review responses

Revision ID: 19665ec864ab
Revises: d204728bf964
Create Date: 2026-08-23 09:26:32.636144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19665ec864ab'
down_revision: Union[str, None] = 'd204728bf964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_responses_question_id'), 'review_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_review_responses_user_id'), 'review_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_responses_viewer_id'), 'review_responses', ['viewer_id'], unique=False)
    op.add_column('courses', sa.Column('pass_ratio', sa.Numeric(precision=3, scale=2), server_default='0.70', nullable=False))
    op.add_column('questions', sa.Column('kind', sa.String(), server_default='assessment', nullable=False))
    op.add_column('questions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: every seed script in backend/scripts/ was written to positions
    # 1-3 review, 4+ assessment (see seed_asc606_construction_intro.sql's
    # header comment) precisely so this could be a WHERE clause. The column
    # default above already typed every existing question 'assessment'; this
    # retypes the review ones.
    op.execute("UPDATE questions SET kind = 'review' WHERE position <= 3")

    # Hand-added: autogenerate does not write CHECK constraints.
    op.create_check_constraint(
        "ck_questions_kind_valid",
        "questions",
        "kind IN ('review', 'assessment')",
    )
    # 6.01.2: 70 percent is a floor a sponsor may raise but not lower.
    op.create_check_constraint(
        "ck_courses_pass_ratio_floor",
        "courses",
        "pass_ratio >= 0.70 AND pass_ratio <= 1.00",
    )


def downgrade() -> None:
    op.drop_constraint("ck_courses_pass_ratio_floor", "courses", type_="check")
    op.drop_constraint("ck_questions_kind_valid", "questions", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'feedback')
    op.drop_column('questions', 'kind')
    op.drop_column('courses', 'pass_ratio')
    op.drop_index(op.f('ix_review_responses_viewer_id'), table_name='review_responses')
    op.drop_index(op.f('ix_review_responses_user_id'), table_name='review_responses')
    op.drop_index(op.f('ix_review_responses_question_id'), table_name='review_responses')
    op.drop_table('review_responses')
    # ### end Alembic commands ###
