"""add video_key to lessons

Revision ID: 4ce352c76df8
Revises: 1f6e7b4faf11
Create Date: 2026-08-04 18:59:46.152429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce352c76df8'
down_revision: Union[str, None] = '1f6e7b4faf11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_key')
    # ### end Alembic commands ###
