"""add subject matter experts, sources, and review chain to courses

Revision ID: 561ad5e4ce3d
Revises: 9dd63108687a
Create Date: 2026-08-18 10:22:48.929550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561ad5e4ce3d'
down_revision: Union[str, None] = '9dd63108687a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_matter_experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_licensed_cpa', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_tax_attorney', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_enrolled_agent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('license_jurisdiction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('citation', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('retrieved_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position')
    )
    op.create_index(op.f('ix_sources_course_id'), 'sources', ['course_id'], unique=False)
    op.add_column('courses', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('content_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('courses', sa.Column('review_cycle', sa.String(), server_default='biennial', nullable=False))
    op.create_index(op.f('ix_courses_developer_id'), 'courses', ['developer_id'], unique=False)
    op.create_index(op.f('ix_courses_reviewer_id'), 'courses', ['reviewer_id'], unique=False)
    op.create_foreign_key(
        'fk_courses_reviewer_id_subject_matter_experts', 'courses', 'subject_matter_experts', ['reviewer_id'], ['id']
    )
    op.create_foreign_key(
        'fk_courses_developer_id_subject_matter_experts', 'courses', 'subject_matter_experts', ['developer_id'], ['id']
    )
    # ### end Alembic commands ###

    # Hand-added: autogenerate does not write CHECK constraints. 4.02, stated
    # directly - a course's developer and reviewer must be different people.
    # Either side being unset (a draft not yet fully staffed) is allowed.
    op.create_check_constraint(
        "ck_courses_developer_reviewer_differ",
        "courses",
        "reviewer_id IS NULL OR developer_id IS NULL OR reviewer_id <> developer_id",
    )
    op.create_check_constraint(
        "ck_courses_review_cycle",
        "courses",
        "review_cycle IN ('annual', 'biennial')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_courses_review_cycle", "courses", type_="check")
    op.drop_constraint("ck_courses_developer_reviewer_differ", "courses", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_courses_developer_id_subject_matter_experts', 'courses', type_='foreignkey')
    op.drop_constraint('fk_courses_reviewer_id_subject_matter_experts', 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_reviewer_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_developer_id'), table_name='courses')
    op.drop_column('courses', 'review_cycle')
    op.drop_column('courses', 'content_updated_at')
    op.drop_column('courses', 'review_notes')
    op.drop_column('courses', 'reviewed_at')
    op.drop_column('courses', 'reviewer_id')
    op.drop_column('courses', 'developer_id')
    op.drop_index(op.f('ix_sources_course_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('subject_matter_experts')
    # ### end Alembic commands ###
