"""create watch progress and required watch ratio

Revision ID: 5a0d4654764a
Revises: d593cd9e3a0e
Create Date: 2026-08-06 10:54:18.295120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0d4654764a'
down_revision: Union[str, None] = 'd593cd9e3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('watched_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'viewer_id')
    )
    op.create_index(op.f('ix_watch_progress_lesson_id'), 'watch_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_viewer_id'), 'watch_progress', ['viewer_id'], unique=False)
    op.add_column('lessons', sa.Column('required_watch_ratio', sa.Float(), server_default='0.9', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'required_watch_ratio')
    op.drop_index(op.f('ix_watch_progress_viewer_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_lesson_id'), table_name='watch_progress')
    op.drop_table('watch_progress')
    # ### end Alembic commands ###
