"""add shuffle seed, viewer id, and retake policy

Revision ID: 76843efbe9ff
Revises: 5a0d4654764a
Create Date: 2026-08-06 11:36:57.238809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76843efbe9ff'
down_revision: Union[str, None] = '5a0d4654764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('viewer_id', sa.UUID(), nullable=True))
    op.add_column('attempts', sa.Column('shuffle_seed', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_attempts_viewer_id'), 'attempts', ['viewer_id'], unique=False)
    op.add_column('lessons', sa.Column('retake_cooldown_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lessons', sa.Column('max_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'max_attempts')
    op.drop_column('lessons', 'retake_cooldown_minutes')
    op.drop_index(op.f('ix_attempts_viewer_id'), table_name='attempts')
    op.drop_column('attempts', 'shuffle_seed')
    op.drop_column('attempts', 'viewer_id')
    # ### end Alembic commands ###
