"""create evaluations

Revision ID: 89972a5eb2c4
Revises: 051cc63bc6c9
Create Date: 2026-08-23 19:51:17.781559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89972a5eb2c4'
down_revision: Union[str, None] = '051cc63bc6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('objectives_met', sa.Integer(), nullable=True),
    sa.Column('prerequisites_appropriate', sa.Integer(), nullable=True),
    sa.Column('materials_relevant', sa.Integer(), nullable=True),
    sa.Column('time_allotted_appropriate', sa.Integer(), nullable=True),
    sa.Column('instructor_effective', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('instructor_effective BETWEEN 1 AND 5', name='ck_evaluations_instructor_effective_range'),
    sa.CheckConstraint('materials_relevant BETWEEN 1 AND 5', name='ck_evaluations_materials_relevant_range'),
    sa.CheckConstraint('objectives_met BETWEEN 1 AND 5', name='ck_evaluations_objectives_met_range'),
    sa.CheckConstraint('prerequisites_appropriate BETWEEN 1 AND 5', name='ck_evaluations_prerequisites_appropriate_range'),
    sa.CheckConstraint('time_allotted_appropriate BETWEEN 1 AND 5', name='ck_evaluations_time_allotted_appropriate_range'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_attempt_id'), 'evaluations', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_attempt_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
