"""add program metadata and learning objectives

Revision ID: 9dd63108687a
Revises: 05e053f86e0a
Create Date: 2026-08-12 07:51:22.156228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd63108687a'
down_revision: Union[str, None] = '05e053f86e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position')
    )
    op.create_index(op.f('ix_learning_objectives_course_id'), 'learning_objectives', ['course_id'], unique=False)
    op.add_column('courses', sa.Column('program_level', sa.String(), server_default='basic', nullable=False))
    op.add_column('courses', sa.Column('field_of_study', sa.String(), server_default='Not CPE eligible', nullable=False))
    op.add_column('courses', sa.Column('prerequisites', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('advance_preparation', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Native Postgres enums are painful to alter, and NASBA revises both of
    # these lists on its own schedule, so validity is a CHECK against the
    # literal values current at the time of this migration (see
    # app/constants/program_levels.py and app/constants/fields_of_study.py)
    # rather than an enum type.
    op.create_check_constraint(
        "ck_courses_program_level",
        "courses",
        "program_level IN ('basic', 'intermediate', 'advanced', 'update', 'overview')",
    )
    op.create_check_constraint(
        "ck_courses_field_of_study",
        "courses",
        "field_of_study IN ("
        "'Not CPE eligible', "
        "'Accounting', 'Accounting (Governmental)', 'Auditing', 'Auditing (Governmental)', "
        "'Business Law', 'Economics', 'Finance', 'Information Technology', "
        "'Management Services', 'Regulatory Ethics', 'Specialized Knowledge', 'Statistics', 'Taxes', "
        "'Behavioral Ethics', 'Business Management & Organization', 'Communications and Marketing', "
        "'Computer Software & Applications', 'Personal Development', 'Personnel/Human Resources', 'Production'"
        ")",
    )


def downgrade() -> None:
    op.drop_constraint("ck_courses_field_of_study", "courses", type_="check")
    op.drop_constraint("ck_courses_program_level", "courses", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'advance_preparation')
    op.drop_column('courses', 'prerequisites')
    op.drop_column('courses', 'field_of_study')
    op.drop_column('courses', 'program_level')
    op.drop_index(op.f('ix_learning_objectives_course_id'), table_name='learning_objectives')
    op.drop_table('learning_objectives')
    # ### end Alembic commands ###
