"""add thumbnail_key to lessons

Revision ID: af95594e5536
Revises: 6f58cd9b86ef
Create Date: 2026-08-11 19:38:31.945924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af95594e5536'
down_revision: Union[str, None] = '6f58cd9b86ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('thumbnail_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'thumbnail_key')
    # ### end Alembic commands ###
