"""add certificate fields to attempts

Revision ID: bce7f146c0a3
Revises: d404797e3faa
Create Date: 2026-08-04 20:18:57.831987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce7f146c0a3'
down_revision: Union[str, None] = 'd404797e3faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('certificate_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_attempts_certificate_code'), 'attempts', ['certificate_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_certificate_code'), table_name='attempts')
    op.drop_column('attempts', 'certificate_code')
    op.drop_column('attempts', 'recipient_name')
    # ### end Alembic commands ###
