"""add credit measurement

Revision ID: d204728bf964
Revises: 561ad5e4ce3d
Create Date: 2026-08-23 08:26:14.366081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd204728bf964'
down_revision: Union[str, None] = '561ad5e4ce3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('credit_award', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('courses', sa.Column('credit_raw_minutes', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('courses', sa.Column('credit_word_count', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_av_seconds', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_question_count', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_formula_version', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('credit_computed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('av_is_additional_learning', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('lessons', sa.Column('word_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'word_count')
    op.drop_column('lessons', 'av_is_additional_learning')
    op.drop_column('courses', 'credit_computed_at')
    op.drop_column('courses', 'credit_formula_version')
    op.drop_column('courses', 'credit_question_count')
    op.drop_column('courses', 'credit_av_seconds')
    op.drop_column('courses', 'credit_word_count')
    op.drop_column('courses', 'credit_raw_minutes')
    op.drop_column('courses', 'credit_award')
    # ### end Alembic commands ###
